# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./Labms_v1.h \
    ./LoginDlg.h \
    ./Singleton.h \
    ./QSQLModule.h
SOURCES += ./main.cpp \
    ./Labms_v1.cpp \
    ./LoginDlg.cpp \
    ./QSQLModule.cpp
FORMS += ./Labms_v1.ui \
    ./LoginDlg.ui
RESOURCES += ./Labms_v1.qrc
